/* The page's only door to the computer: one window.hub object whose every
   call is a named IPC request handled in main.js. */
const { contextBridge, ipcRenderer } = require('electron');

const call = (name, args) => ipcRenderer.invoke(name, args || {});

contextBridge.exposeInMainWorld('hub', {
  repos: {
    cached: () => call('repos:cached'),
    scan: () => call('repos:scan'),
    status: (dir) => call('repos:status', { dir }),
    statusMany: (dirs) => call('repos:statusMany', { dirs }),
    log: (dir, n) => call('repos:log', { dir, n }),
    diff: (dir, file) => call('repos:diff', { dir, file }),
    fetch: (dir) => call('repos:fetch', { dir }),
    pull: (dir) => call('repos:pull', { dir }),
    updateOne: (dir) => call('repos:updateOne', { dir }),
    commit: (dir, message) => call('repos:commit', { dir, message }),
    push: (dir) => call('repos:push', { dir }),
    sync: (dir, message) => call('repos:sync', { dir, message }),
    setRemote: (dir, url) => call('repos:setRemote', { dir, url }),
    clearLock: (dir) => call('repos:clearLock', { dir }),
    setHidden: (dir, hide) => call('repos:setHidden', { dir, hide }),
    setCommands: (dir, commands) => call('repos:setCommands', { dir, commands }),
    settings: () => call('repos:settings'),
    saveSettings: (patch) => call('repos:saveSettings', patch),
    addFolder: (dir) => call('repos:addFolder', { dir }),
    clone: (url, parent) => call('repos:clone', { url, parent }),
    runOptions: (dir) => call('repos:runOptions', { dir }),
  },
  gh: {
    preview: (link) => call('gh:preview', { link }),
    parse: (link) => call('gh:parse', { link }),
  },
  explain: {
    local: (dir) => call('explain:local', { dir }),
    facts: (info) => call('explain:facts', { info }),
    summary: (key) => call('explain:summary', { key }),
    claude: (args) => call('explain:claude', args),
  },
  job: {
    start: (dir, command) => call('job:start', { dir, command }),
    stop: (dir) => call('job:stop', { dir }),
    running: () => call('job:running'),
    onEvent: (cb) => ipcRenderer.on('job:event', (_e, msg) => cb(msg)),
  },
  term: { open: (dir, command) => call('term:open', { dir, command }) },
  sandbox: {
    status: () => call('sandbox:status'),
    plan: (args) => call('sandbox:plan', args),
    start: (cloneUrl, repo, plan) => call('sandbox:start', { cloneUrl, repo, plan }),
    list: () => call('sandbox:list'),
    attach: (name) => call('sandbox:attach', { name }),
    remove: (name) => call('sandbox:remove', { name }),
    removeAll: () => call('sandbox:removeAll'),
    shell: (name) => call('sandbox:shell', { name }),
    preview: (url, title) => call('sandbox:preview', { url, title }),
    openBrowser: (url) => call('sandbox:openBrowser', { url }),
    extend: (name, minutes) => call('sandbox:extend', { name, minutes }),
    saveLog: (name) => call('sandbox:saveLog', { name }),
    explainFailure: (args) => call('explain:failure', args),
    onEvent: (cb) => ipcRenderer.on('sandbox:event', (_e, msg) => cb(msg)),
  },
  auth: {
    status: () => call('auth:status'),
    signIn: () => call('auth:signIn'),
    signOut: () => call('auth:signOut'),
    openCliLogin: () => call('auth:openCliLogin'),
    onChanged: (cb) => ipcRenderer.on('auth:changed', (_e, msg) => cb(msg)),
  },
  insights: { get: (link, force) => call('insights:get', { link, force }) },
  files: {
    refs: (link) => call('files:refs', { link }),
    tree: (link, ref) => call('files:tree', { link, ref }),
    file: (link, ref, path) => call('files:file', { link, ref, path }),
    localTree: (dir) => call('files:localTree', { dir }),
    localFile: (dir, path) => call('files:localFile', { dir, path }),
    save: (name, text) => call('files:save', { name, text }),
  },
  saved: {
    all: () => call('saved:all'),
    save: (full, opts) => call('saved:save', { full, ...(opts || {}) }),
    unsave: (full) => call('saved:unsave', { full }),
    createCollection: (name) => call('saved:createCollection', { name }),
    renameCollection: (id, name) => call('saved:renameCollection', { id, name }),
    deleteCollection: (id) => call('saved:deleteCollection', { id }),
    visit: (full, snap) => call('saved:visit', { full, snap }),
    clearHistory: () => call('saved:clearHistory'),
    exportFile: (format, collectionId) => call('saved:export', { format, collectionId }),
  },
  settings: {
    get: () => call('settings:get'),
    set: (patch) => call('settings:set', { patch }),
    reset: (keys) => call('settings:reset', { keys }),
    popout: () => call('settings:popout'),
    closePopout: () => call('settings:closePopout'),
    clearData: (what) => call('settings:clearData', { what }),
    onChanged: (cb) => ipcRenderer.on('settings:changed', (_e, v) => cb(v)),
    onPopped: (cb) => ipcRenderer.on('settings:popped', (_e, v) => cb(v)),
  },
  installers: {
    check: () => call('installers:check'),
    install: (ids) => call('installers:install', { ids }),
    signIn: (id) => call('installers:signIn', { id }),
  },
  appControl: {
    reload: () => call('app:reload'),
    relaunch: () => call('app:relaunch'),
    devtools: () => call('app:devtools'),
  },
  open: {
    folder: (dir) => call('open:folder', { dir }),
    web: (url) => call('open:web', { url }),
    editor: (dir) => call('open:editor', { dir }),
  },
  pickFolder: (title, defaultPath) => call('dialog:pickFolder', { title, defaultPath }),
  tools: {
    check: () => call('tools:check'),
    identity: () => call('tools:identity'),
    setIdentity: (name, email) => call('tools:setIdentity', { name, email }),
  },
  app: {
    defaultCloneDir: () => call('app:defaultCloneDir'),
    setCloneDir: (dir) => call('app:setCloneDir', { dir }),
    version: () => call('app:version'),
  },
});
